#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo -e "\n🤖 [ precommit hook ] linting before committing..."
npm run lint && \
echo -e "🤖 ✅ [ precommit hook ] lint encountered no blocking issues\n" || \
echo -e "🤖 🚨 [ precommit hook ] lint encountered blocking issues\n"