#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🤖 [ precommit hook ] linting before committing..."
npm run lint && \
echo "🤖 ✅ [ precommit hook ] lint encountered no blocking issues" || \
echo "🤖 🚨 [ precommit hook ] lint encountered blocking issues"